type: aws-lambda

inputTypes:
  name:
    type: string
    required: false
    default: func-${self.instanceId}
  memory:
    type: number
    required: true
  timeout:
    type: number
    required: true
  description:
    type: string
    required: false
  handler:
    type: string
    required: true
  role:
    type: object
    required: false
  env:
    type: object
    required: false
