name: AwsSnsTopic
extends: Component
version: 0.3.0
main: ./dist/index.js

description: 'Provision AWS SNS Topic with the Serverless Framework'
license: Apache-2.0
author: 'Serverless, Inc. <hello@serverless.com> (https://serverless.com)'
repository: 'github:serverless/components'

provider: ${inputs.provider}
topicName: ${inputs.topicName}
displayName: ${inputs.displayName}
policy: ${inputs.policy}
deliveryPolicy: ${inputs.deliveryPolicy}
deliveryStatusAttributes: ${inputs.deliveryStatusAttributes}

inputTypes:
  provider:
    type: AwsProvider
    required: true
    displayName: AWS Provider
    description: The AWSProvider instance that contains the credentials for AWS
  topicName:
    type: string
    required: false
    description: The name of your SNS topic
    displayName: SNS Topic Name
    example: my-project-sns-${self.instanceId}
  displayName:
    type: string
    required: false
    displayName: SNS Topic Display Name
    description: The display name of your SNS topic
    example: My SNS Topic display name
  policy:
    type: object
    required: false
    displayName: SNS Policy
    description: The policy for your SNS topic
    example:
      Version: '2008-10-17'
      Id: policy_id
      Statement:
        - Effect: Allow
          Sid: statement_id
          Principal:
            AWS: '*'
          Action:
            - SNS:Publish
            - SNS:RemovePermission
            - SNS:SetTopicAttributes
            - SNS:DeleteTopic
            - SNS:ListSubscriptionsByTopic
            - SNS:GetTopicAttributes
            - SNS:Receive
            - SNS:AddPermission
            - SNS:Subscribe
          Resource: arn:aws:sns:us-east-1:000000000000:my-sns-topic
          Condition:
            StringEquals:
              AWS:SourceOwner: '000000000000'
  deliveryPolicy:
    type: object
    required: false
    displayName: SNS Delivery Policy
    description: The delivery policy for your SNS topic
    example:
      http:
        defaultHealthyRetryPolicy:
          minDelayTarget: 20
          maxDelayTarget: 20
          numRetries: 3
          numMaxDelayRetries: 0
          numNoDelayRetries: 0
          numMinDelayRetries: 2
          backoffFunction: linear
        disableSubscriptionOverrides: true
        defaultThrottlePolicy:
          maxReceivesPerSecond: 3
  deliveryStatusAttributes:
    type: array
    required: false
    displayName: SNS Delivery Status Attributes
    description: Delivery status attributes for your SNS topic
    example:
      - ApplicationSuccessFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-success-feedback-role
        ApplicationSuccessFeedbackSampleRate: 100
        ApplicationFailureFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-failure-feedback-role
      - HTTPSuccessFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-success-feedback-role
        HTTPSuccessFeedbackSampleRate: 100
        HTTPFailureFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-failure-feedback-role
      - LambdaSuccessFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-success-feedback-role
        LambdaSuccessFeedbackSampleRate: 100
        LambdaFailureFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-success-feedback-role
      - SQSSuccessFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-success-feedback-role
        SQSSuccessFeedbackSampleRate: 100
        SQSFailureFeedbackRoleArn: arn:aws:iam::000000000000:role/sns-success-feedback-role
