language: node_js
sudo: false
node_js:
- 8
install:
- npm install
- pushd examples/restapi/code && npm install && popd
script:
- npm run lint
- npm test
env:
  SENTRY_DSN: https://17031d90871a4daebd4f261f2359b38f:9ce69587851c448b96893fb3794df20e@sentry.io/300239
  SEGMENT_WRITE_KEY: jvOP27GTlIJubkJpRcDAa4uSfwCD03NI
deploy:
  provider: npm
  email: services@serverless.com
  skip_cleanup: true
  on:
    branch: master
    tags: true
    repo: serverless/components
  api_key:
    secure: O5NpK/+yZUc4n6UQHVN8Vp4q2tl0NPqLLh3voyS1L9+rYF2+aBukPHyinfAage+TwnCFYO8nX7W+yxHcddU73TU4V0yOzZDnJjxhglomg8Xkcfbrl2HN6Br3PrKjUv3ugXM9O5NJuzpIDuxJ+JvWazZOCieQif/ZfUbB2GkpYOSTJ0l7VWLCuQW2VLJS2EJZ7J4Oje7L+qaRJuDu952leYDkOrqdfm3/CFmoxel/QmXlrldQnYMu6mFgzSXSIIWtGErA95yFwFdkZOwgUw+TwyHCPAoOziL+HV8gM4Y+CIDYa81gnYXAp+6e09X52GD6wht7QJx2ELoarZuehXSnrlmoxYKyCYnx/NOZ5j8klP5ZRRYy3iBqiuur96ibIQWW2Qm6CG7LHR3uELYD49r2WPDEBieq7IubyCfTnORwLX3DcCukaGIEdI6fWTGTLaLBJIBdHtYMoTAVYMLcnmYFnKFD34kwPhnJWiJbrl4rwTihq99Ipc5LsVVlMyJNr5IIezYy1gANbdkTfFjIYW+Nufry0JrBs0fQF9PzdYbA77yW5xZWKPdiXRkVArrtT+NkAYx6iL9VK9AGAF26BfGuZBPbXx7O9KKgl/KdfxP+tjCaGozl30YZv1gheGBvM2SrxkpK43sFftqMgUr3nI+wuvBa40oW3avt6SYlsEYwQbE=
