version: '3'
services:
  serverless-components:
    build:
      context: ./
    working_dir: /app
    container_name: serverless-components
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - ~/.aws/:/root/.aws
      - ~/.gcloud/:/root/.gcloud
      - ~/.gitconfig:/root/.gitconfig
