type: aws-lambda
version: 0.2.0
core: 0.2.x

description: "AWS Lambda Serverless Component"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    default: func-${self.instanceId}
    displayName: Lambda function name
    description: The Lambda function name
    example: myProject-functionName-${self.instanceId}
  memory:
    type: number
    required: true
    displayName: Memory size
    description: The functions memory size in Megabyte
    example: 512
  timeout:
    type: number
    required: true
    displayName: Function timeout
    description: The function execution time at which Lambda should terminate the function
    example: 3
  runtime:
    type: string
    required: true
    default: nodejs8.10
    displayName: Function runtime
    description: |
      Runtime for the function.
      Possible values are java8, nodejs6.10, nodejs8.10, python2.7, python3.6 and dotnetcore1.0
    example: nodejs8.10
  description:
    type: string
    displayName: Lambda function description
    description: |
      A short, user-defined function description.
      Lambda does not use this value. Assign a meaningful description as you see fit
    example: The function that does XYZ to ABC
  handler:
    type: string
    required: true
    displayName: Handler
    description: The path to the exported handler function
    example: products.create
  root:
    type: string
    displayName: Path to source code
    example: ${self.path}/code
  role:
    type: object
    displayName: Lambda IAM role
    description: |
      The Amazon Resource Name (ARN) of the IAM role that Lambda assumes
      when it executes your function to access any other Amazon Web Services (AWS) resources
  env:
    type: object
    displayName: Environment variables
    description: Lambda functions environment's configuration settings
    example:
      foo: true
      tableName: products-${self.appId}

outputTypes:
  arn:
    type: string
    description: The Lambda functions arn
  roleArn:
    type: string
    description: The arn of the created / managed role the Lambda function uses
