name: AwsS3Website
extends: Component
main: ./dist/index.js
version: 0.3.0

provider: ${inputs.provider}
bucket: ${inputs.bucket}

inputTypes:
  provider:
    type: AwsProvider
    required: true
  bucket:
    type: string
    displayName: Bucket Name
    description: Your AWS S3 bucket name, which is also used as a domain.
    required: true
  projectDir:
    type: string
    displayName: Project directory
    description: Root location of web project
    required: true
  assets:
    type: string
    displayName: Assets
    description: Path to static website assets. Can be absolute or relative to projectDir.
    required: false
    default: .
  envFileLocation:
    type: string
    displayName: Env File Location
    description: File path where environment script will be saved. Can be absolute or relative to projectDir.
    required: true
  env:
    type: object
    displayName: Environment Variables
    description: Environment variables to be included in a script with the front-end assets
    required: false
  buildCmd:
    type: string
    displayName: Build command
    description: Command to execute before packaging and uploading site files. Executed in the projectDir.
    required: false
