type: blog-app
version: 0.0.1

components:
  blogSite:
    type: static-website
    inputs:
      name: blog-site
      contentPath: ${self.path}/site
      templateValues: {}
      contentIndex: index.html
      contentError: error.html
      hostingRegion: us-east-1
      hostingDomain: sls-blog-${self.serviceId}.example.com
      aliasDomain: www.sls-blog-${self.serviceId}.example.com
