type: s3-dirloader
version: 0.2.0
core: 0.2.x

description: "S3 directory loader"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  contentPath:
    type: string
    required: true
  bucketName:
    type: string
    required: true
