type: aws-s3-bucket

inputTypes:
  name:
    type: string
    required: false
    default: bucket-${self.instanceId}
    displayName: S3 Bucket Name
    description: The name of your s3 bucket. Name must be globally unique in AWS
    example: my-project-bucket-${self.instanceId}
