type: aws-s3-bucket
version: 0.2.0
core: 0.2.x

description: "Provision AWS s3 buckets with serverless components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    required: false
    default: bucket-${self.instanceId}
    displayName: S3 Bucket Name
    description: The name of your s3 bucket. Name must be globally unique in AWS
    example: my-project-bucket-${self.instanceId}
