name: landing-page
component: website
org: serverlessinc
description: Deploys a serverless website on AWS
keywords: aws, serverless, website, frontend
repo: https://github.com/serverless-components/website
license: MIT

inputs:
  src:
    src: ./src
    hook: npm run build
    dist: ./dist
