type: tests-integration-function-mock
version: 0.0.1

inputTypes:
  name:
    type: string
    required: true
  memorySize:
    type: number
    default: 512
  timeout:
    type: number
    default: 60
  environment:
    type: object
    default:
      isMock: true
      variables:
        key1: value1
  role:
    type: string

outputTypes:
  id:
    type: string
  name:
    type: string
  memorySize:
    type: number
  timeout:
    type: number
  environment:
    type: object
  role:
    type: string
  deploymentCounter:
    type: number
  defaultRole:
    type: any
