type: cloudflare-workers
version: 1.0.0
description: 'Serverless components to deploy Cloudflare-Workers'

inputTypes:
        zone_id:
                type: string
                required: true
        script_path:
                type: string
                required: true

outputTypes:
        success:
                type: boolean
                description: If worker script has been successfully deployed
        result:
                type: any
                description: The resultant worker script uploaded
        errors:
                type: any
                description: A list of error messages
        messages:
                type: any
                description: Messages

