type: aws-ecs-service
version: 0.2.0
core: 0.2.x

description: "Provision AWS ECS Service with Serverless Components"
license: Apache-2.0
author: "Serverless Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  serviceName:
    type: string
    required: true
    example: myAwsEcsService
    description: The name of your service. Up to 255 letters (uppercase and lowercase), numbers, hyphens, and underscores are allowed. Service names must be unique within a cluster, but you can have similarly named services in multiple clusters within a Region or across multiple Regions.
  cluster:
    type: string
    description: The short name or full Amazon Resource Name (ARN) of the cluster on which to run your service. If you do not specify a cluster, the default cluster is assumed.
  launchType:
    type: string
    enum: [EC2, FARGATE]
    description: The launch type on which to run your service.
    example: FARGATE
  deploymentConfiguration:
    type: object
    description: Optional deployment parameters that control how many tasks run during the deployment and the ordering of stopping and starting tasks.
  desiredCount:
    type: integer
    description: The number of instantiations of the specified task definition to place and keep running on your cluster.
    example: 10
  healthCheckGracePeriodSeconds:
    type: integer
    description: The period of time, in seconds, that the Amazon ECS service scheduler should ignore unhealthy Elastic Load Balancing target health checks after a task has first started. This is only valid if your service is configured to use a load balancer. If your service's tasks take a while to start and respond to Elastic Load Balancing health checks, you can specify a health check grace period of up to 7,200 seconds during which the ECS service scheduler ignores health check status. This grace period can prevent the ECS service scheduler from marking tasks as unhealthy and stopping them before they have time to come up.
  networkConfiguration:
    type: object
    description: The network configuration for the service. This parameter is required for task definitions that use the awsvpc network mode to receive their own Elastic Network Interface, and it is not supported for other network modes
  placementConstraints:
    type: array
    description: An array of placement constraint objects to use for tasks in your service. You can specify a maximum of 10 constraints per task (this limit includes constraints in the task definition and those specified at run time).
  placementStrategy:
    type: array
    description: The placement strategy objects to use for tasks in your service. You can specify a maximum of five strategy rules per service.
  platformVersion:
    type: string
    description: The platform version on which to run your service. If one is not specified, the latest version is used by default.
  role:
    type: string
    description: The name or full Amazon Resource Name (ARN) of the IAM role that allows Amazon ECS to make calls to your load balancer on your behalf. This parameter is only permitted if you are using a load balancer with your service and your task definition does not use the awsvpc network mode. If you specify the role parameter, you must also specify a load balancer object with the loadBalancers parameter.
      If your specified role has a path other than /, then you must either specify the full role ARN (this is recommended) or prefix the role name with the path. For example, if a role with the name bar has a path of /foo/ then you would specify /foo/bar as the role name. For more information, see Friendly Names and Paths in the IAM User Guide.
  schedulingStrategy:
    type: string
    enum: [REPLICA, DAEMON]
    description: The scheduling strategy to use for the service. For more information, see Services.
      There are two service scheduler strategies available,
      REPLICA-The replica scheduling strategy places and maintains the desired number of tasks across your cluster. By default, the service scheduler spreads tasks across Availability Zones. You can use task placement strategies and constraints to customize task placement decisions.
      DAEMON-The daemon scheduling strategy deploys exactly one task on each active container instance that meets all of the task placement constraints that you specify in your cluster. When using this strategy, there is no need to specify a desired number of tasks, a task placement strategy, or use Service Auto Scaling policies.
      Note, Fargate tasks do not support the DAEMON scheduling strategy.
  serviceRegistries:
    type: array
    description: The details of the service discovery registries to assign to this service. For more information, see Service Discovery.
  taskDefinition:
    type: any
    required: true
    example: ${myECSTaskDefinition}
    description: A reference to an AWS ECS TaskDefinition component, the family and revision (family:revision) or full ARN of the task definition to run in your service. If a revision is not specified, the latest ACTIVE revision is used.
  loadBalancers:
    type: array
    description: A load balancer object representing the load balancer to use with your service. Currently, you are limited to one load balancer or target group per service. After you create a service, the load balancer name or target group ARN, container name, and container port specified in the service definition are immutable.
      For Classic Load Balancers, this object must contain the load balancer name, the container name (as it appears in a container definition), and the container port to access from the load balancer. When a task from this service is placed on a container instance, the container instance is registered with the load balancer specified here.
      For Application Load Balancers and Network Load Balancers, this object must contain the load balancer target group ARN, the container name (as it appears in a container definition), and the container port to access from the load balancer. When a task from this service is placed on a container instance, the container instance and port combination is registered as a target in the target group specified here.
      Services with tasks that use the awsvpc network mode (for example, those with the Fargate launch type) only support Application Load Balancers and Network Load Balancers; Classic Load Balancers are not supported. Also, when you create any target groups for these services, you must choose ip as the target type, not instance, because tasks that use the awsvpc network mode are associated with an elastic network interface, not an Amazon EC2 instance.

outputTypes:
  serviceArn:
    type: string
    description: The ARN that identifies the service. The ARN contains the arn:aws:ecs namespace, followed by the Region of the service, the AWS account ID of the service owner, the service namespace, and then the service name. For example, arn:aws:ecs:region:012345678910:service/my-service .
  serviceName:
    type: string
    description: The name of your service. Up to 255 letters (uppercase and lowercase), numbers, hyphens, and underscores are allowed. Service names must be unique within a cluster, but you can have similarly named services in multiple clusters within a Region or across multiple Regions.
  events:
    type: array
    description: The event stream for your service. A maximum of 100 of the latest events are displayed.
  clusterArn:
    type: string
    description: The Amazon Resource Name (ARN) of the cluster that hosts the service.
  loadBalancers:
    type: array
    description: A list of Elastic Load Balancing load balancer objects, containing the load balancer name, the container name (as it appears in a container definition), and the container port to access from the load balancer.
      Services with tasks that use the awsvpc network mode (for example, those with the Fargate launch type) only support Application Load Balancers and Network Load Balancers; Classic Load Balancers are not supported. Also, when you create any target groups for these services, you must choose ip as the target type, not instance, because tasks that use the awsvpc network mode are associated with an elastic network interface, not an Amazon EC2 instance.
  serviceRegisteries:
    type: string
    description: Array of ServiceRegistry objects
  status:
    type: string
    enum: [ACTIVE, DRAINING, INACTIVE]
    description: The status of the service. The valid values are ACTIVE, DRAINING, or INACTIVE.
  desiredCount:
    type: integer
    description: The desired number of instantiations of the task definition to keep running on the service.
  runningCount:
    type: integer
    description: The number of tasks in the cluster that are in the RUNNING state.
  pendingCount:
    type: integer
    description: The number of tasks in the cluster that are in the PENDING state.
  launchType:
    type: string
    description: The launch type on which your service is running.
  platformVersion:
    type: string
    description: The platform version on which your task is running.
  taskDefinition:
    type: string
    description: The task definition to use for tasks in the service.
  deploymentConfiguration:
    type: object
    description: Optional deployment parameters that control how many tasks run during the deployment and the ordering of stopping and starting tasks.
  deployments:
    type: array
    description: The current state of deployments for the service.
  roleArn:
    type: string
    description: The ARN of the IAM role associated with the service that allows the Amazon ECS container agent to register container instances with an Elastic Load Balancing load balancer.
  createdAt:
    type: any
    description: The Unix time stamp for when the service was created.
  placementConstraints:
    type: array
    description: The placement constraints for the tasks in the service.
  placementStrategy:
    type: array
    description: The placement strategy that determines how tasks for the service are placed.
  networkConfiguration:
    type: object
    description: The VPC subnet and security group configuration for tasks that receive their own elastic network interface by using the awsvpc networking mode.
  healthCheckGracePeriodSeconds:
    type: integers
    description: The period of time, in seconds, that the Amazon ECS service scheduler ignores unhealthy Elastic Load Balancing target health checks after a task has first started.
  schedulingStrategy:
    type: string
    description: The scheduling strategy to use for the service. For more information, see Services.
      There are two service scheduler strategies available,
      REPLICA-The replica scheduling strategy places and maintains the desired number of tasks across your cluster. By default, the service scheduler spreads tasks across Availability Zones. You can use task placement strategies and constraints to customize task placement decisions.
      DAEMON-The daemon scheduling strategy deploys exactly one task on each active container instance that meets all of the task placement constraints that you specify in your cluster. When using this strategy, there is no need to specify a desired number of tasks, a task placement strategy, or use Service Auto Scaling policies.
      Note, Fargate tasks do not support the DAEMON scheduling strategy.

