type: Component
name: AwsRoute53
version: 0.2.0
core: 0.2.x

description: "Provision AWS route53 definitions with serverless components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  domainName:
    type: string
    displayName: Domain name
    description: The domain name used in route 53
    example: www.defaultdomain.com
  dnsName:
    type: string
    displayName: DNS name
    description: The DNS name used in route 53
    example: d111111abcdef8.cloudfront.net
  privateZone:
    type: boolean
    displayName: Private Zone
    description: Whether this is a private zone
    example: false
  vpcId:
    type: string
    displayName: VPC Id
    description: The VPC's Id
    example: my-existing-vpc-id
  vpcRegion:
    type: string
    displayName: VPC Region
    description: The VPC's region
    example: mydefaultvpcregion

outputTypes:
  hostedZone:
    type: object
    description: The hosted zone configuration
  changeRecordSet:
    type: object
    description: The change record set
