type: s3-policy
version: 0.2.0
core: 0.2.x

description: "A Serverless Component for AWS S3 Policy Documents"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  bucketName:
    type: string
    required: true
