name: AwsIamPolicy
extends: Component
main: ./dist/index.js
version: 0.3.0

description: "Provision AWS IAM Policies with the Serverless Framework"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

provider: ${inputs.provider}
policyName: ${inputs.policyName}
document: ${inputs.document}

inputTypes:
  provider:
    type: AwsProvider
    required: true
  document:
    type: object
    required: true
    displayName: IAM Policy Document
    description: The JSON policy document that you want to use as the content for the new policy
  policyName:
    type: string
    required: false
    displayName: IAM Policy Name
    description: The friendly name of the policy

