type: aws-iam-policy
version: 0.2.0
core: 0.2.x

description: "Provision AWS IAM Policies with serverless components"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  name:
    type: string
    default: policy-${self.instanceId}
    displayName: IAM Policy Name
    description: The friendly name of the policy
  document:
    type: object
    required: true
    displayName: IAM Policy Document
    description: The JSON policy document that you want to use as the content for the new policy
