type: aws-iam-policy

inputTypes:
  name:
    type: string
    default: policy-${self.instanceId}
    displayName: IAM Policy Name
    description: The friendly name of the policy
  document:
    type: object
    required: true
    displayName: IAM Policy Document
    description: The JSON policy document that you want to use as the content for the new policy
