name: dynamodb-table
component: aws-dynamodb
org: serverlessinc
description: Deploys a serverless NoSQL database powered by AWS DynamoDB
keywords: aws, serverless, nosql, database
repo: https://github.com/serverless-components/aws-dynamodb
license: MIT

inputs:
  deletionPolicy: delete # allows table to be removed. This property is a safe guard.
  attributeDefinitions:
    - AttributeName: attribute1
      AttributeType: S
    - AttributeName: attribute2
      AttributeType: N
  keySchema:
    - AttributeName: attribute1
      KeyType: HASH
    - AttributeName: attribute2
      KeyType: RANGE
  region: us-east-1
