component: aws-dynamodb
name: my-table

inputs:
  deletionPolicy: delete # allows table to be removed. This property is a safe guard.
  attributeDefinitions:
    - AttributeName: attribute1
      AttributeType: S
    - AttributeName: attribute2
      AttributeType: N
  keySchema:
    - AttributeName: attribute1
      KeyType: HASH
    - AttributeName: attribute2
      KeyType: RANGE
  region: us-east-1
