type: twilio-application

inputTypes:
  accountSid:
    type: string
    required: true
    description: "The unique id of the Account responsible for this application."
  authToken:
    type: string
    required: true
    description: "The auth token."
  friendlyName:
    type: string
    required: true
    description: "A human readable description of the new application. Maximum 64 characters."
  apiVersion:
    type: string
    required: false
    description: "Requests to this application's URLs will start a new TwiML session with this API version. Either 2010-04-01 or 2008-08-01. Defaults to your account's default API version."
  voiceUrl:
    type: string
    required: false
    description: "The URL that Twilio should request when somebody dials a phone number assigned to this application."
  voiceMethod:
    type: string
    required: false
    description: "The HTTP method that should be used to request the VoiceUrl. Must be either GET or POST. Defaults to POST."
  voiceFallbackUrl:
    type: string
    required: false
    description: "A URL that Twilio will request if an error occurs requesting or executing the TwiML at Url."
  voiceFallbackMethod:
    type: string
    required: false
    description: "The HTTP method that should be used to request the VoiceFallbackUrl. Either GET or POST. Defaults to POST."
  statusCallback:
    type: string
    required: false
    description: "The URL that Twilio will request to pass status parameters (such as call ended) to your application."
  statusCallbackMethod:
    type: string
    required: false
    description: "The HTTP method Twilio will use to make requests to the StatusCallback URL. Either GET or POST. Defaults to POST."
  voiceCallerIdLookup:
    type: boolean
    required: false
    description: "Do a lookup of a caller's name from the CNAM database and post it to your app. Either true or false. Defaults to false."
  smsUrl:
    type: string
    required: false
    description: "The URL that Twilio should request when somebody sends an SMS to a phone number assigned to this application."
  smsMethod:
    type: string
    required: false
    description: "The HTTP method Twilio will use when making requests to the SmsUrl. Either GET or POST."
  smsFallbackUrl:
    type: string
    required: false
    description: "The URL that Twilio will request if an error occurs retrieving or executing the TwiML from SmsUrl."
  smsFallbackMethod:
    type: string
    required: false
    description: "The HTTP method Twilio will use when requesting the above URL. Either GET or POST."
  smsStatusCallback:
    type: string
    required: false
    description: "The URL that Twilio will POST to when a message is sent via the /SMS/Messages endpoint if you specify the Sid of this application on an outgoing SMS request."
  messageStatusCallback:
    type: string
    required: false
    description: "Twilio will make a POST request to this URL to pass status parameters (such as sent or failed) to your application if you use the /Messages endpoint to send the message and specify this application's Sid as the ApplicationSid on an outgoing SMS request."


outputTypes:
  sid:
    type: string
    description: "The SID of your twilio application"
  uri:
    type: string
    description: "The URI of your twilio application"
  dateCreated:
    type: string
    description: "The date the application was created"
  dateUpdated:
    type: string
    description: "The date the application was updated"
  accountSid:
    type: string
    description: "The unique id of the Account responsible for this application."
  friendlyName:
    type: string
    description: "A human readable description of the new application. Maximum 64 characters."
  apiVersion:
    type: string
    description: "Requests to this application's URLs will start a new TwiML session with this API version. Either 2010-04-01 or 2008-08-01. Defaults to your account's default API version."
  voiceUrl:
    type: string
    description: "The URL that Twilio should request when somebody dials a phone number assigned to this application."
  voiceMethod:
    type: string
    description: "The HTTP method that should be used to request the VoiceUrl. Must be either GET or POST. Defaults to POST."
  voiceFallbackUrl:
    type: string
    description: "A URL that Twilio will request if an error occurs requesting or executing the TwiML at Url."
  voiceFallbackMethod:
    type: string
    description: "The HTTP method that should be used to request the VoiceFallbackUrl. Either GET or POST. Defaults to POST."
  statusCallback:
    type: string
    description: "The URL that Twilio will request to pass status parameters (such as call ended) to your application."
  statusCallbackMethod:
    type: string
    description: "The HTTP method Twilio will use to make requests to the StatusCallback URL. Either GET or POST. Defaults to POST."
  voiceCallerIdLookup:
    type: boolean
    description: "Do a lookup of a caller's name from the CNAM database and post it to your app. Either true or false. Defaults to false."
  smsUrl:
    type: string
    description: "The URL that Twilio should request when somebody sends an SMS to a phone number assigned to this application."
  smsMethod:
    type: string
    description: "The HTTP method Twilio will use when making requests to the SmsUrl. Either GET or POST."
  smsFallbackUrl:
    type: string
    description: "The URL that Twilio will request if an error occurs retrieving or executing the TwiML from SmsUrl."
  smsFallbackMethod:
    type: string
    description: "The HTTP method Twilio will use when requesting the above URL. Either GET or POST."
  smsStatusCallback:
    type: string
    description: "The URL that Twilio will POST to when a message is sent via the /SMS/Messages endpoint if you specify the Sid of this application on an outgoing SMS request."
  messageStatusCallback:
    type: string
    description: "Twilio will make a POST request to this URL to pass status parameters (such as sent or failed) to your application if you use the /Messages endpoint to send the message and specify this application's Sid as the ApplicationSid on an outgoing SMS request."
