type: my-project
version: 0.0.1

components:
  myFunction:
    type: aws-lambda@0.2.0
    inputs:
      memory: 512
      timeout: 10
      handler: handler.handler
      role:
        arn: ${myRole.arn}
  myRole:
    type: aws-iam-role@0.2.0
    inputs:
      service: lambda.amazonaws.com
  myBucket:
    type: AwsS3Bucket
    inputs: ...
